title: "Rare Union: Content Strategy Consulting and Workshops"
email: sara@rareunion.com
description: > # this means to ignore newlines until "baseurl:"
  Rare Union provides content strategy consulting, training, and workshops on topics like intro to content strategy, content and UX, information architecture, and structured content modeling.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.rareunion.com/" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: sara_ann_marie
github_username: sarawb

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
sass:
  style: compressed

assets:
  sources:
    - _assets/webfonts
    - _assets/javascripts
    - _assets/stylesheets
